User_Accounts/urls.py
from django.urls import path,include
from .import views  #Login,Create_user,Logout_User


app_name='User_Accounts'
urlpatterns=[
    path('', views.Home.as_view(), name='Home'),
    path('signup/', views.Create_user.as_view(), name='Signup'),
    path('login/', views.Login_User.as_view(), name='Login'),
    path('<str:uuid>/profile/', views.Detail_profile.as_view(), name='Profile'),
    path('profile/<str:pk>/edit/', views.Edit_profile.as_view(), name='Edit_profile'),
    path('logout/', views.Logout_User, name='Logout'),
    # path('api/',include(api.urls)),
]

blog_post/urls.py
from django.urls import path
from . import views

app_name='Blog_post'
urlpatterns=[
    path('',views.Home_page.as_view(),name='Home_Page'),
    path('blog-post/',views.Blog_Post.as_view(),name='Create_blog'),
    path('list/',views.List_blog.as_view(),name='List_blog'),
    path('<str:slug>/detail/',views.Detail_blog.as_view(),kwargs={'view':'Detail_page'},name='Detail_blog'),
    path('<str:slug>/edit/',views.Detail_blog.as_view(),kwargs={'view':'Edit_page'},name='Edit_blog'),
]

blog_post_pro/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import settings,static,serve

admin.site.site_header='Blog_Post Admin'
admin.site.site_title='Blog_posts Admin portal'
admin.site.index_title='Blog_post Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog_post.urls')),
    #path('blog/',include('blog_post.urls')),
    path('accounts/',include('User_Accounts.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns+=[
        re_path(r'^profile/(?P<path>.*)$',serve,{'document_root':'settings.MEDIA_ROOT'})
    ]

templates/Accounts/Home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ tittle }}</title>
</head>
<body>
    <h5>welcome to the home of login page {{ user }}</h5>
    {% if user.is_authenticated %}
        <a href="{% url 'User_Accounts:Profile'  user.id %}">profile</a>
        <a href="{% url 'User_Accounts:Edit_profile'  user.id %}">Update</a>
        <a href="{% url 'User_Accounts:Logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'User_Accounts:Login' %}">Login</a>
    {% endif %}
</body>
</html>

templates/Accounts/Login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ tittle }}</title>
</head>
<body>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <center>
            <input type="submit" value="Login">
            <input type="reset" value="cancel">
        </center>
    </form>
</body>
</html>

templates/Accounts/Signup.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ tittle }}</title>
</head>
<body>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <center>
            <input type="submit" value="Login">
            <input type="reset" value="cancel">
        </center>
    </form>
</body>
</html>

templates/Accounts/edit_profile.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ tittle }}</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <center>
            <input type="submit" value="submit">
            <input type="reset" value="cancel">
        </center>
    </form>
</body>
</html>

templates/Accounts/profile.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ tittle }}</title>
</head>
<body>
    <h3>Welcome to profile of {{ user.username }}</h3>
</body>
</html>